defmodule Groupchat.Repo.Migrations.AddUserIdToAssistants do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:assistants) do
      add :user_id,
          references(:users,
            column: :id,
            name: "assistants_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:assistants, "assistants_user_id_fkey")

    alter table(:assistants) do
      remove :user_id
    end
  end
end
