defmodule Groupchat.Repo.Migrations.AddDefaultAssistantToUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :default_assistant_id,
          references(:assistants,
            column: :id,
            name: "users_default_assistant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    alter table(:assistants) do
      modify :model, :text, default: "gpt-4o"
    end
  end

  def down do
    alter table(:assistants) do
      modify :model, :text, default: nil
    end

    drop constraint(:users, "users_default_assistant_id_fkey")

    alter table(:users) do
      remove :default_assistant_id
    end
  end
end
